// praxiteles/src/components/Diagram.svelte
<script>
    import mermaid from 'mermaid';


    mermaid.initialize({
        startOnLoad: true,
        theme: 'dark',
        htmlLabels: true,
        gantt: {
            titleTopMargin: 50,
            barHeight: 30,
            barGap: 20,
            topPadding: 75,
            rightPadding: 75,
            leftPadding: 75,
            fontSize: 15,
            sectionFontSize: 25,
            gridLineStartPadding: 20,
        }
    });


    export let mermaidDiagram; // Accepting the JSON string as a prop
    let mermaidContainer;

    async function renderDiagram() {
        const x = Math.floor(Math.random()*5000);
        const { svg } = await mermaid.render("diagram"+x, mermaidDiagram);
        mermaidContainer.innerHTML = svg;
    }

    $: if (mermaidDiagram) {
        try {
            renderDiagram();
        } catch (error) {
            console.error('Invalid JSON:', error);
            // Instead of setting mermaidDiagram to '', consider handling the error differently
        }
    }


</script>

<pre bind:this={mermaidContainer} class="mermaid">
</pre>

<style>
    .mermaid {
        width: 90%;
        margin: auto;
        overflow: auto;
    }
</style>

// polykleitos/src/components/Diagram.vue
<template>
  <div ref="mermaidContainer" class="mermaid-diagram"></div>
</template>

<script setup>
import { ref, watch, onMounted, nextTick } from 'vue';
import mermaid from 'mermaid';

const props = defineProps({
  mermaidDiagram: {
    type: String,
    required: true
  }
});

const mermaidContainer = ref(null);

onMounted(() => {
  mermaid.initialize({ startOnLoad: false });
  renderDiagram();
});

watch(() => props.mermaidDiagram, () => {
  renderDiagram();
});

async function renderDiagram() {
  if (mermaidContainer.value && props.mermaidDiagram) {
    mermaidContainer.value.innerHTML = '';
    await nextTick();

    try {
      const { svg } = await mermaid.render('mermaid-' + Date.now(), props.mermaidDiagram);
      mermaidContainer.value.innerHTML = svg;
    } catch (error) {
      console.error('Mermaid rendering error:', error);
      mermaidContainer.value.innerHTML = '<p>Error rendering diagram</p>';
    }
  }
}
</script>

<style scoped>
.mermaid-diagram {
  width: 100%;
  overflow-x: auto;
}
</style>
